service: org-news

plugins:
  - serverless-plugin-scripts
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-plugin-chrome

package:
  exclude:
    - ./**
    - "!dist/**"
    - "!node_modules/**"
    - node_modules/puppeteer/.local-chromium/**

provider:
  name: aws
  stage: ${{opt:stage, 'dev'}}
  region: ${{opt:region, 'eu-north-1'}}

  environment:
    accountId: "#{AWS::AccountId}"
    region: "#{AWS::Region}"

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"

  stackTags:
    SERVICE: ${{self:service}}
    STAGE: ${{self:provider.stage}}
    REGION: ${{self:provider.region}}
    VERSION: ${{file(./package.json):version}}

  runtime: nodejs8.10
  memorySize: 768
  timeout: 60

custom:
  scripts:
    hooks:
      "before:deploy:createDeploymentArtifacts": yarn run build

functions:
  fetch-news:
    handler: dist/index.fetchNewsHandler
    events:
      - sns: fetch-news