service: org-tasker

plugins:
  - serverless-plugin-scripts
  - serverless-pseudo-parameters

package:
  exclude:
    - ./**
    - "!dist/**"
    - "!node_modules/**"

provider:
  name: aws
  stage: ${{opt:stage, 'dev'}}
  region: ${{opt:region, 'eu-north-1'}}

  environment:
    accountId: "#{AWS::AccountId}"
    region: "#{AWS::Region}"

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

  # use ${{}} to access serverless variables
  # this is necessary because cloudformation uses ${} syntax
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"

  stackTags:
    SERVICE: ${{self:service}}
    STAGE: ${{self:provider.stage}}
    REGION: ${{self:provider.region}}
    VERSION: ${{file(./package.json):version}}

  runtime: nodejs8.10
  memorySize: 256
  timeout: 3

custom:
  scripts:
    hooks:
      "before:deploy:createDeploymentArtifacts": yarn run build

functions:
  publish-tasks:
    handler: dist/index.tasker
    # events:
    #   - schedule: rate(1 hour)
